

name: 'dbt_snowflake_tagging'
version: '1.0.1'
config-version: 2

profile: 'dbt_snowflake_tagging'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:      
  - "target"
  - "dbt_packages"

models:
  dbt_snowflake_tagging:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: table

on-run-end: 
  - "{{apply_pii_tags_models(results)}}"